Small typos in doc
orkes-io/docs pull request #110
Opened 2022-06-07 09:40 UTC by Riuqlav

Small typos in the doc, I did not modify any code.

2022-06-07 15:02 UTC, dougsillars requested changes
Thanks for the edits - these are great!

I have one change to request however:

in the introduction.md = all your edits are fine -except "What is Conductor" is grammatically correct, whereas your change of "what is the conductor" is not (Conductor is the product we are talking about)

2022-06-08 21:22 UTC, Riuqlav commented
Some more small ones

2022-06-09 13:56 UTC, dougsillars requested changes
These are all great - thank you for your efforts in making our docs better.
I left a few more comments/suggestions.

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/fork-task.md
> +the task also collects outputs from each of the forked tasks or sub workflows.
This change will now read "The JOIN the task also collects outputs from each of the forked tasks or sub workflows.

The old version was "The `JOIN`task also collects outputs from each of the forked tasks or sub workflows."

I think the old version is correct

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/do-while-task.md
> +When scheduled, each task of this loop will see its `taskReferenceName` concatenated with \_\_i, with i being the iteration number, starting at 1. Warning: taskReferenceName containing arithmetic ope
We don't need to escape the characters in the docs - it adds confusion to the reader (IMO)

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/do-while-task.md
> +- SUB_WORKFLOW is unsupported;
this is an error.. can you please remove this line (subworkflows are supported)

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/dynamic-fork-task.md
> +A Fork operation in the conductor, lets you run a specified list of other tasks or sub workflows in parallel after the forked
Conductor is the name of the tool.  
I think perhaps:
"A Fork operation in Conductor lets you run a specified list of other tasks..."
reads better (capitalized Conductor and removed the comma)

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/dynamic-fork-task.md
> +the task also collects outputs from each of the forked tasks or sub workflows.
"The `JOIN` the task also collects.."

I don't think this is correct.

2022-06-09 13:56 UTC, dougsillars commented on docs/reference-docs/dynamic-fork-task.md
> +single image resizes task does one job. The `FORK_JOIN_DYNAMIC` and the following `JOIN` will manage the multiple
I think this should be singular.  the task does a resize on just one image.  single image resize.

2023-04-27 09:37 UTC, closed without merging